version: '3.8'

services:
  postgres-gorm:
    image: postgres:latest
    container_name: postgres-gorm
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data-gorm:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin-gorm:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-gorm
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres-gorm
    restart: unless-stopped

volumes:
  postgres_data-gorm: